### ISSUE TITLE
Installation notes and issues

### ISSUE THREAD

**Issue by Natkeeran** [jefferyb/islandora-7.x-enterprise-ansible#2]
I have successfully installed the islandora full stack using this ansible playbook.  I've installed on Ubuntu 16.04 (Digital Ocean).  Thank you for the nice work.  Some issues I encountered along the way.

1.  Cannot find the path in the following task.  The path is different for php7.
name: Increase the maximum file size settings in Drupal
https://github.com/jefferyb/islandora-7.x-enterprise-ansible/blob/master/roles/islandora-drupal/tasks/main.yml#L158

2. Tomcat fails to start
```
TASK [islandora-solr : Wait for tomcat] ****************************************
fatal: [##.##.##.##]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for search string Server startup in /var/lib/tomcat7/logs/catalina.out"}
	to retry, use: --limit @/home/nat/ansible/islandora-7.x-enterprise-ansible/install-islandora-7.x-enterprise.retry
```
Tomcat is not starting off properly.  Could be related to this issue: https://confluence.atlassian.com/crowdkb/crowd-startup-takes-an-extremely-long-time-on-linux-762872528.html

As that was the last few tasks, I started the Tomcat manually and completed the rest of the 2 tasks manually as well.

3. When going to the Islandora Repositories in Drupal, I get the following error:
```
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'drupal7.xml_form_builder_form_associations' doesn't exist: SELECT fa.* FROM {xml_form_builder_form_associations} fa WHERE ( (content_model = :db_condition_placeholder_0) ); Array ( [:db_condition_placeholder_0] => islandora:collectionCModel ) in xml_form_builder_get_database_associations() (line 90 of /var/www/html/sites/all/modules/islandora_xml_forms/builder/includes/associations.inc).
```
I disabled it the "Islandora XML Form Builder" module, then I was able to browse the repository.

I think the third issue is related to this one: https://groups.google.com/forum/#!msg/islandora/ihY1xM-iWs4/vMs0uFrXAwAJ

As per this thread https://www.drupal.org/node/2657070, converting the primary keys in https://github.com/Islandora/islandora_xml_forms/blob/7.x/builder/xml_form_builder.install to 'not null' => True resolved the issue.  Lower case null, upper case does not work for some reason!

**Comment by jefferyb** [comment]
Thanks @Natkeeran for reporting your findings and referencing solutions to them... That helped a lot in fixing them...

I think it's all fixed now... You can try it out and if you find anything else, please don't hesitate to let me know...
Thanks again,
-Jeffery
